application:
  image: tombradyfacts:latest
  ports:
  - '8080'

database:
  image: mysql
  ports:
     - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 'pass'
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'pass'
