version: '3'
services:

  application:
    image: tombradyfacts:latest
    ports:
    - '8080:8080'
    depends_on:
    - db


  db:
    image: mysql
    ports:
       - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "facts"
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'brady'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
